#!/bin/bash

cd "`dirname "$0"`/.."

mkdir -p var/ssh
cd var/ssh

if [ -e id_rsa -a ! -f id_rsa ]; then
    rm -rf id_rsa
fi

if [ -e id_rsa.pub -a ! -f id_rsa.pub ]; then
    rm -rf id_rsa.pub
fi

if [ ! -f id_rsa ]; then
    rm -f id_rsa.pub
    ssh-keygen -P "" -f ./id_rsa
elif [ ! -f id_rsa.pub ]; then
    ssh-keygen -f id_rsa -y > id_rsa.pub
fi
