menu:
  - name: zadání
    route: assignments
    routes: ["new-assignment", "assignment-detail", "assignment"]
    roles: ['ROLE_TEACHER']
  - name: odevzdané práce
    route: all-submissions
    routes: ["submission-detail"]
    roles: ['ROLE_TEACHER']
  - name: odevzdat
    route: submit
    routes: ['create-submission', 'submission-close']
    roles: ['ROLE_STUDENT']
  - name: moje práce
    route: submissions
    routes: ['submission-detail']
    roles: ['ROLE_STUDENT']
  - name: uživatelé
    route: users
    routes: ["user"]
    roles: ['ROLE_ADMIN']
  - name: adminer
    route: adminer-frame
    roles: ['ROLE_SUPERADMIN']
  - name: synchronizace
    route: sync-info
    roles: ['ROLE_SUPERADMIN']
  - name: detail uživatele
    route: user_detail
    roles: ['ROLE_USER']
    hidden: true
