#!/bin/bash

if [ "$1" == "prod" ]; then
    flags="--no-interaction --no-dev"
    composer dump-env prod
    lib/asset-update
else
    flags=""
    test -f .env.local.php && rm -f .env.local.php
    lib/asset-update remove
fi

composer install $flags

